{"uid":"99b95cbf3d3c1db","name":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","fullName":"OdinUiTests.Tests.Activity.TestActivityStatusWithTwoOrMoreAttemptsTests.Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","historyId":"OdinUiTests.Tests.Activity.TestActivityStatusWithTwoOrMoreAttemptsTests.Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695626942477,"stop":1695627043382,"duration":100905},"status":"failed","statusMessage":"System.AggregateException : One or more errors occurred. (Request timed out)\n  ----> System.TimeoutException : Request timed out\n  ----> System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.\n  ----> System.TimeoutException : A task was canceled.\n  ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.","statusTrace":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at System.Threading.Tasks.Task`1.get_Result()\n   at OdinUiTests.Services.ExamineeService.FinishAttempt(UsersEnum user, String resultId) in /azp/_work/1/s/Services/ExamineeService.cs:line 107\n   at OdinUiTests.Services.ExamineeService.CheckTestHasOneAttempt(String actId, UsersEnum user) in /azp/_work/1/s/Services/ExamineeService.cs:line 83\n   at OdinUiTests.Tests.Activity.TestActivityStatusWithTwoOrMoreAttemptsTests.StatusExistIfAtLeastOneCompletedAttempt(String actId) in /azp/_work/1/s/Tests/Activity/TestActivityTests.cs:line 650\n--TimeoutException\n   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--TaskCanceledException\n   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   at RestSharp.RestClient.ExecuteRequestAsync(RestRequest request, CancellationToken cancellationToken)\n--TimeoutException\n\n--TaskCanceledException\n   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"OneTimeSetUp","time":{"start":1695627043382,"stop":1695627043382,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"SetUp","time":{"start":1695627043382,"stop":1695627043382,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"System.AggregateException : One or more errors occurred. (Request timed out)\n  ----> System.TimeoutException : Request timed out\n  ----> System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.\n  ----> System.TimeoutException : A task was canceled.\n  ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.","statusTrace":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at System.Threading.Tasks.Task`1.get_Result()\n   at OdinUiTests.Services.ExamineeService.FinishAttempt(UsersEnum user, String resultId) in /azp/_work/1/s/Services/ExamineeService.cs:line 107\n   at OdinUiTests.Services.ExamineeService.CheckTestHasOneAttempt(String actId, UsersEnum user) in /azp/_work/1/s/Services/ExamineeService.cs:line 83\n   at OdinUiTests.Tests.Activity.TestActivityStatusWithTwoOrMoreAttemptsTests.StatusExistIfAtLeastOneCompletedAttempt(String actId) in /azp/_work/1/s/Tests/Activity/TestActivityTests.cs:line 650\n--TimeoutException\n   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--TaskCanceledException\n   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   at RestSharp.RestClient.ExecuteRequestAsync(RestRequest request, CancellationToken cancellationToken)\n--TimeoutException\n\n--TaskCanceledException\n   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)","steps":[{"name":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695626942477,"stop":1695627043382,"duration":100905},"status":"failed","statusMessage":"System.AggregateException : One or more errors occurred. (Request timed out)\n  ----> System.TimeoutException : Request timed out\n  ----> System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.\n  ----> System.TimeoutException : A task was canceled.\n  ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.","statusTrace":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at System.Threading.Tasks.Task`1.get_Result()\n   at OdinUiTests.Services.ExamineeService.FinishAttempt(UsersEnum user, String resultId) in /azp/_work/1/s/Services/ExamineeService.cs:line 107\n   at OdinUiTests.Services.ExamineeService.CheckTestHasOneAttempt(String actId, UsersEnum user) in /azp/_work/1/s/Services/ExamineeService.cs:line 83\n   at OdinUiTests.Tests.Activity.TestActivityStatusWithTwoOrMoreAttemptsTests.StatusExistIfAtLeastOneCompletedAttempt(String actId) in /azp/_work/1/s/Tests/Activity/TestActivityTests.cs:line 650\n--TimeoutException\n   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--TaskCanceledException\n   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)\n   at RestSharp.RestClient.ExecuteRequestAsync(RestRequest request, CancellationToken cancellationToken)\n--TimeoutException\n\n--TaskCanceledException\n   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)","steps":[],"attachments":[{"uid":"a83977f9b92bab47","name":"StatusExistIfAtLeastOneCompletedAttempt.jpg","source":"a83977f9b92bab47.jpg","type":"image/jpeg","size":314006},{"uid":"bbc8ac4c69ff2c8e","name":"Console Output","source":"bbc8ac4c69ff2c8e.txt","type":"text/plain","size":30}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":2,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"TearDown","time":{"start":1695627043382,"stop":1695627043382,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"thread","value":"ParallelWorker#3"},{"name":"host","value":"eeb97404b430"},{"name":"package","value":"OdinUiTests.Tests.Activity"},{"name":"testMethod","value":"StatusExistIfAtLeastOneCompletedAttempt"},{"name":"testClass","value":"TestActivityStatusWithTwoOrMoreAttemptsTests"},{"name":"tag","value":"Активность"},{"name":"tag","value":"Дежурство"},{"name":"tag","value":"Регресс"},{"name":"parentSuite","value":"Активность"},{"name":"suite","value":"Контрольная"},{"name":"subSuite","value":"Прохождение теста"},{"name":"severity","value":"critical"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"Param #0","value":"5209"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"1d2793975b5ada3b","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695626157928,"stop":1695626169470,"duration":11542}}],"categories":[{"name":"Test Defects","messageRegex":".*","matchedStatuses":["failed"],"flaky":false}],"history":{"statistic":{"failed":5,"broken":0,"skipped":0,"passed":44,"unknown":0,"total":49},"items":[{"uid":"99b1f3ff5ba1e8a4","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695620642575,"stop":1695620651528,"duration":8953}},{"uid":"6ba95f0dcbae04ea","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695361077730,"stop":1695361089024,"duration":11294}},{"uid":"5b017d23e8584379","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695314772526,"stop":1695314782345,"duration":9819}},{"uid":"7e0de89da540bfb2","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695297325103,"stop":1695297334796,"duration":9693}},{"uid":"70c99bfafd5137d7","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695097893844,"stop":1695097906575,"duration":12731}},{"uid":"ca9d34d6a539ccf3","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695040399304,"stop":1695040422691,"duration":23387}},{"uid":"bc8c0ff930557049","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1695027897721,"stop":1695027909367,"duration":11646}},{"uid":"cb9e95574ac5ec15","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1694580530724,"stop":1694580545592,"duration":14868}},{"uid":"a497c7e943d8a854","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1693801581054,"stop":1693801595692,"duration":14638}},{"uid":"99d8e4bf642558e4","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1693554940171,"stop":1693554950681,"duration":10510}},{"uid":"810cb2b3bedcef54","status":"failed","statusDetails":"OpenQA.Selenium.ElementClickInterceptedException : element click intercepted: Element <div data-v-422f06fd=\"\">...</div> is not clickable at point (1051, 416). Other element would receive the click: <div data-v-ad7fb932=\"\" class=\"q-card__section q-card__section--vert text-center q-pa-none\">...</div>\n  (Session info: headless chrome=115.0.5790.110)","time":{"start":1693322363633,"stop":1693322370467,"duration":6834}},{"uid":"f1d1a2b94a43d767","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1693196602733,"stop":1693196613041,"duration":10308}},{"uid":"9aac1355a46a96bd","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692940756065,"stop":1692940765859,"duration":9794}},{"uid":"c9677ec5ed15fdd8","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692852334571,"stop":1692852344482,"duration":9911}},{"uid":"2ea6030b0f0fc95a","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692844050022,"stop":1692844060239,"duration":10217}},{"uid":"44d15c81ad04bf63","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692775508053,"stop":1692775522676,"duration":14623}},{"uid":"d27ad617dddee07","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692766292085,"stop":1692766308565,"duration":16480}},{"uid":"7c10f8f9138f9a0b","status":"failed","statusDetails":"System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')","time":{"start":1692594597775,"stop":1692594598366,"duration":591}},{"uid":"cfb49a63f15e0551","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692246820252,"stop":1692246834683,"duration":14431}},{"uid":"5fd6980ba3fb92a8","status":"passed","statusDetails":"Страница индивидуальной контрольной: статус отображается, если есть хотя бы одна завершенная попытка","time":{"start":1692161429954,"stop":1692161439031,"duration":9077}}]},"tags":["Регресс","Дежурство","Активность"]},"source":"99b95cbf3d3c1db.json","parameterValues":["5209"]}